Feat/lidar car
RoboJackets/roboracing-software pull request #393
Opened 2021-08-22 14:54 UTC by idale0001

Updated opponent detection files so that the opponents are more consistently assigned the same id and color by using a greedy algorithm to find the clusters that are closest to the previous clusters.

2021-08-29 22:19 UTC, NicoBartholomai requested changes
There is a faster way to find pairs between two sets but I think since they're so small this is fine. You could consider creating your own datatype that just holds a pointer to the clusters and their respective centroids instead of trying to keep track of the same index within lists.

2021-08-31 00:36 UTC, Daniel-Martin576 commented on rr_evgp/src/opponent_detection/opponent_detection.cpp
> +        }
max

2021-08-31 00:36 UTC, Daniel-Martin576 commented on rr_evgp/src/opponent_detection/opponent_detection.cpp
> +        }
Could do transform if wanted to be fancy, but not nessessary

2021-08-31 00:36 UTC, Daniel-Martin576 commented on rr_evgp/src/opponent_detection/opponent_detection.cpp
> +        }
Const reference

2021-11-07 21:49 UTC, NicoBartholomai commented
This will be re-implemented in ROS 2

2021-11-07 21:49 UTC, closed without merging